import { Product, Category } from './types';

export const staticCategories: Category[] = [
  { id: 1, name: 'Smartphones', slug: 'smartphones' },
  { id: 2, name: 'Laptops', slug: 'laptops' },
  { id: 3, name: 'Audio', slug: 'audio' },
  { id: 4, name: 'Cameras', slug: 'cameras' },
  { id: 5, name: 'Clothing', slug: 'clothing' },
  { id: 6, name: 'Shoes', slug: 'shoes' },
  { id: 7, name: 'Watches', slug: 'watches' },
  { id: 8, name: 'Furniture', slug: 'furniture' },
  { id: 9, name: 'Kitchen', slug: 'kitchen' },
  { id: 10, name: 'Books', slug: 'books' },
];

export const staticProducts: Product[] = [
  // Smartphones
  { id: 1, title: 'Samsung Galaxy S24 Ultra', description: 'Flagship smartphone with 200MP camera, S Pen, and Snapdragon 8 Gen 3 processor. 12GB RAM, 256GB storage, 6.8-inch Dynamic AMOLED display. Titanium frame with IP68 water resistance.', price: 124999, discountPercentage: 10, rating: 4.8, stock: 50, brand: 'Samsung', thumbnail: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 2, title: 'iPhone 15 Pro Max', description: 'Apple A17 Pro chip with titanium design. 48MP main camera with 5x optical zoom. USB-C with USB 3 speeds. Action Button for quick controls. 6.7-inch Super Retina XDR display with ProMotion.', price: 159900, discountPercentage: 5, rating: 4.9, stock: 30, brand: 'Apple', thumbnail: 'https://images.unsplash.com/photo-1695048132969-7b99f3935c59?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 3, title: 'OnePlus 12 5G', description: 'Snapdragon 8 Gen 3 with Hasselblad tuned triple camera. 50W wireless charging and 100W wired charging. 6.82-inch 2K AMOLED 120Hz display. Up to 16GB RAM and 512GB storage.', price: 64999, discountPercentage: 12, rating: 4.7, stock: 80, brand: 'OnePlus', thumbnail: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 4, title: 'Google Pixel 8 Pro', description: 'Google Tensor G3 chip with advanced AI features. 50MP main, 48MP ultra-wide, 48MP telephoto camera system. 7 years of Android updates. Temperature sensor. Magic Eraser and Best Take features.', price: 89999, discountPercentage: 15, rating: 4.6, stock: 45, brand: 'Google', thumbnail: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 5, title: 'Xiaomi 14 Pro', description: 'Snapdragon 8 Gen 3 with Leica optics. 50MP triple camera with 1-inch main sensor. 120W HyperCharge wired and 50W wireless. 6.73-inch LTPO AMOLED 2K display with 1-120Hz.', price: 84999, discountPercentage: 8, rating: 4.5, stock: 60, brand: 'Xiaomi', thumbnail: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 6, title: 'Vivo X100 Pro', description: 'MediaTek Dimensity 9300 with ZEISS optics. 50MP gimbal-style stabilized main camera. V3 imaging chip for ultra-stable video. 6.78-inch AMOLED 120Hz display. 100W fast charging.', price: 89999, discountPercentage: 7, rating: 4.6, stock: 35, brand: 'Vivo', thumbnail: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 7, title: 'Realme GT 5 Pro', description: 'Snapdragon 8 Gen 3 with periscope telephoto. 50MP main with Sony IMX890 sensor. 144Hz LTPO AMOLED display. 100W SuperVOOC charging. Under-display fingerprint scanner.', price: 49999, discountPercentage: 18, rating: 4.4, stock: 90, brand: 'Realme', thumbnail: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 8, title: 'OPPO Find X7 Ultra', description: 'Snapdragon 8 Gen 3 with Hasselblad quad cameras. Dual periscope telephoto lenses. 6.82-inch LTPO3 AMOLED 2K display. 100W SuperVOOC and 50W AIRVOOC wireless charging.', price: 109999, discountPercentage: 6, rating: 4.7, stock: 25, brand: 'OPPO', thumbnail: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },

  // Laptops
  { id: 9, title: 'MacBook Pro 14" M3 Pro', description: 'Apple M3 Pro chip with 11-core CPU and 14-core GPU. 18GB unified memory, 512GB SSD. Liquid Retina XDR display with ProMotion. 18-hour battery life. MagSafe charging.', price: 199900, discountPercentage: 5, rating: 4.9, stock: 20, brand: 'Apple', thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 10, title: 'Dell XPS 15 OLED', description: 'Intel Core i9-13900H with NVIDIA RTX 4070. 32GB DDR5 RAM, 1TB NVMe SSD. 15.6-inch 3.5K OLED touchscreen. 86Whr battery with 130W charging. Premium aluminium chassis.', price: 189999, discountPercentage: 10, rating: 4.7, stock: 15, brand: 'Dell', thumbnail: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 11, title: 'ASUS ROG Zephyrus G14', description: 'AMD Ryzen 9 7940HS with NVIDIA RTX 4060. 16GB DDR5, 1TB SSD. 14-inch 2560x1600 165Hz Mini LED display. AniMe Matrix LED lid. Compact gaming powerhouse at 1.65kg.', price: 134999, discountPercentage: 12, rating: 4.8, stock: 25, brand: 'ASUS', thumbnail: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 12, title: 'HP Spectre x360 14', description: 'Intel Core Ultra 7 with Intel Arc graphics. 32GB LPDDR5 RAM, 2TB SSD. 14-inch 2.8K OLED 120Hz touch display. 360-degree hinge convertible. Tile tracker built-in.', price: 174999, discountPercentage: 8, rating: 4.6, stock: 18, brand: 'HP', thumbnail: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 13, title: 'Lenovo ThinkPad X1 Carbon', description: 'Intel Core i7-1365U with Intel Iris Xe. 32GB LPDDR5 RAM, 1TB SSD. 14-inch 2.8K OLED display. MIL-SPEC tested durability. 57Whr battery with 65W USB-C charging. Only 1.12kg.', price: 159999, discountPercentage: 7, rating: 4.7, stock: 22, brand: 'Lenovo', thumbnail: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 14, title: 'MSI Titan GT77 HX', description: 'Intel Core i9-13980HX with NVIDIA RTX 4090. 64GB DDR5 RAM, 4TB NVMe SSD. 17.3-inch 4K 144Hz Mini LED display. Per-key RGB mechanical keyboard. Desktop-level gaming performance.', price: 329999, discountPercentage: 5, rating: 4.8, stock: 8, brand: 'MSI', thumbnail: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 15, title: 'Acer Swift X 14', description: 'AMD Ryzen 7 7745HX with NVIDIA RTX 4070. 16GB DDR5, 1TB SSD. 14.5-inch 2.8K OLED 120Hz display. Slim 17.9mm chassis at 1.6kg. 76Wh battery. Creator laptop with premium display.', price: 109999, discountPercentage: 15, rating: 4.5, stock: 30, brand: 'Acer', thumbnail: 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },

  // Audio
  { id: 16, title: 'Sony WH-1000XM5', description: 'Industry-leading noise cancelling headphones. 30-hour battery life. Multipoint connection for 2 devices. Crystal clear hands-free calling. Speak-to-chat technology. Foldable premium design.', price: 29990, discountPercentage: 20, rating: 4.9, stock: 100, brand: 'Sony', thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
  { id: 17, title: 'Apple AirPods Pro 2nd Gen', description: 'Active Noise Cancellation with Transparency mode. Adaptive Audio adjusts based on surroundings. Personalized Spatial Audio. H2 chip for next-level performance. 30-hour total battery with case.', price: 24900, discountPercentage: 8, rating: 4.8, stock: 150, brand: 'Apple', thumbnail: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
  { id: 18, title: 'Bose QuietComfort 45', description: 'Premium noise cancelling headphones with 24-hour battery. Aware Mode for hearing your surroundings. TriPort acoustic architecture. Foldable design with premium ear cushions. USB-C charging.', price: 26900, discountPercentage: 15, rating: 4.7, stock: 75, brand: 'Bose', thumbnail: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
  { id: 19, title: 'Samsung Galaxy Buds2 Pro', description: '360-degree audio with head tracking. Intelligent ANC with 3-mic system. 24-bit Hi-Fi sound. IPX7 water resistance. Ear canal fit detection. 8-hour earbuds + 21-hour case battery.', price: 17999, discountPercentage: 25, rating: 4.6, stock: 120, brand: 'Samsung', thumbnail: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
  { id: 20, title: 'JBL Flip 6', description: 'Portable Bluetooth speaker with powerful JBL Pro Sound. IP67 waterproof and dustproof. 12 hours of playtime. PartyBoost feature to link multiple speakers. USB-C charging. Compact cylindrical design.', price: 9999, discountPercentage: 22, rating: 4.7, stock: 200, brand: 'JBL', thumbnail: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
  { id: 21, title: 'Marshall Emberton II', description: 'Portable Bluetooth speaker with Marshall signature sound. 30 hours of playtime. IP67 waterproof rating. True Wireless Stereo mode. Multi-directional sound. USB-C charging.', price: 14999, discountPercentage: 10, rating: 4.8, stock: 60, brand: 'Marshall', thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
  { id: 22, title: 'Sennheiser HD 660S2', description: 'Open-back audiophile headphones with balanced 4.4mm and 6.35mm connectors. 38 ohm impedance for easy driving. New transducer design with extended bass. Premium velour ear pads. Detachable cable.', price: 44990, discountPercentage: 5, rating: 4.9, stock: 25, brand: 'Sennheiser', thumbnail: 'https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },

  // Cameras
  { id: 23, title: 'Sony Alpha A7 IV', description: 'Full-frame 33MP BSI CMOS sensor. 4K 60fps video recording. 759-point phase detection AF. Real-time Eye AF for humans and animals. 5-axis in-body stabilization. Dual SD card slots.', price: 259990, discountPercentage: 5, rating: 4.9, stock: 15, brand: 'Sony', thumbnail: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400', images: [], category: { id: 4, name: 'Cameras', slug: 'cameras' }, categoryId: 4 },
  { id: 24, title: 'Canon EOS R6 Mark II', description: 'Full-frame 24.2MP CMOS sensor. Up to 40fps with electronic shutter. 4K 60fps video. Dual Pixel CMOS AF II with subject tracking. 6.5-stop IBIS. Dual card slots (CFexpress + SD).', price: 229990, discountPercentage: 7, rating: 4.8, stock: 12, brand: 'Canon', thumbnail: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400', images: [], category: { id: 4, name: 'Cameras', slug: 'cameras' }, categoryId: 4 },
  { id: 25, title: 'Nikon Z8', description: 'Full-frame 45.7MP stacked BSI CMOS sensor. 8K RAW video internally. 20fps continuous shooting. 493-point phase detection AF. Pre-capture feature. Weather-sealed body. Dual CFexpress slots.', price: 349990, discountPercentage: 3, rating: 4.9, stock: 8, brand: 'Nikon', thumbnail: 'https://images.unsplash.com/photo-1571768127822-d8958bf4e009?w=400', images: [], category: { id: 4, name: 'Cameras', slug: 'cameras' }, categoryId: 4 },
  { id: 26, title: 'Fujifilm X-T5', description: 'APS-C 40.2MP X-Trans BSI CMOS 5 HR sensor. 6.2K video recording. 7-stop IBIS. Film Simulation modes. 15fps mechanical shutter. Compact rangefinder-style body. Dual SD card slots.', price: 164990, discountPercentage: 8, rating: 4.8, stock: 20, brand: 'Fujifilm', thumbnail: 'https://images.unsplash.com/photo-1581591524425-c7e0978865fc?w=400', images: [], category: { id: 4, name: 'Cameras', slug: 'cameras' }, categoryId: 4 },
  { id: 27, title: 'GoPro Hero 12 Black', description: '5.3K60 video and 27MP photos. HyperSmooth 6.0 stabilization. HDR video support. Waterproof to 10m without housing. Enduro battery with extended cold weather performance. GP-Log for color grading.', price: 44999, discountPercentage: 12, rating: 4.7, stock: 80, brand: 'GoPro', thumbnail: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=400', images: [], category: { id: 4, name: 'Cameras', slug: 'cameras' }, categoryId: 4 },

  // Clothing
  { id: 28, title: 'Nike Air Max 270 React T-Shirt', description: 'Premium cotton-polyester blend with moisture-wicking Dri-FIT technology. Raglan sleeves for full range of motion. Reflective details for low-light visibility. Machine washable.', price: 2999, discountPercentage: 30, rating: 4.5, stock: 500, brand: 'Nike', thumbnail: 'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 29, title: 'Levi\'s 501 Original Jeans', description: 'The original blue jean since 1873. 100% cotton denim with iconic straight leg fit. Button fly closure. Five-pocket styling. Available in multiple washes. Shrink-to-fit technology.', price: 5999, discountPercentage: 20, rating: 4.6, stock: 300, brand: 'Levi\'s', thumbnail: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 30, title: 'Adidas Ultraboost 23 Hoodie', description: 'Made with Primeblue yarn containing Parley Ocean Plastic. Regular fit with kangaroo pocket. Drawcord adjustable hood. Ribbed cuffs and hem. 70% recycled materials. UPF 50+ sun protection.', price: 7999, discountPercentage: 25, rating: 4.4, stock: 200, brand: 'Adidas', thumbnail: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 31, title: 'H&M Premium Slim-Fit Shirt', description: 'Slim-fit shirt in easy-iron cotton poplin. Spread collar with button cuffs. Chest pocket. Machine washable. Available in multiple colors. Perfect for formal and semi-formal occasions.', price: 1999, discountPercentage: 35, rating: 4.3, stock: 400, brand: 'H&M', thumbnail: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 32, title: 'Zara Structured Blazer', description: 'Single-breasted blazer with structured shoulders. Notched lapel with flap pockets. Interior lining with breast pocket. Padded shoulders for clean silhouette. Button fastening. Dry clean only.', price: 8999, discountPercentage: 15, rating: 4.5, stock: 150, brand: 'Zara', thumbnail: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 33, title: 'Puma Essential Logo Tee', description: 'Regular fit cotton jersey t-shirt. PUMA Cat logo on chest. Ribbed crew neck. Tagless design for comfort. Available in 12 colors. 100% cotton for breathability and comfort.', price: 1499, discountPercentage: 40, rating: 4.2, stock: 600, brand: 'Puma', thumbnail: 'https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 34, title: 'Raymond Formal Suit', description: 'Premium wool-blend formal suit with single-breasted jacket. Two-button closure with notched lapels. Flat-front trousers with side pockets. Dry clean only. Available in navy, charcoal, and black.', price: 14999, discountPercentage: 20, rating: 4.7, stock: 80, brand: 'Raymond', thumbnail: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4939?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },

  // Shoes
  { id: 35, title: 'Nike Air Jordan 1 Retro High OG', description: 'The shoe that started it all. Premium leather upper with Air-Sole cushioning. Perforated toe box for breathability. Nike Air cushioning in heel. Durable rubber outsole with pivot point.', price: 12999, discountPercentage: 10, rating: 4.8, stock: 60, brand: 'Nike', thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', images: [], category: { id: 6, name: 'Shoes', slug: 'shoes' }, categoryId: 6 },
  { id: 36, title: 'Adidas Ultraboost 23', description: 'Primeknit+ upper that moves with your foot. Boost midsole for incredible energy return. Continental rubber outsole for grip. Linear Energy Push system for propulsive toe-off. Fits true to size.', price: 17999, discountPercentage: 15, rating: 4.7, stock: 80, brand: 'Adidas', thumbnail: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400', images: [], category: { id: 6, name: 'Shoes', slug: 'shoes' }, categoryId: 6 },
  { id: 37, title: 'New Balance 990v6', description: 'Made in USA with premium pigskin leather and mesh upper. ENCAP midsole with polyurethane for durability. Blown rubber outsole for traction. Dual-density collar foam. ABZORB crash pad.', price: 22999, discountPercentage: 8, rating: 4.9, stock: 40, brand: 'New Balance', thumbnail: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=400', images: [], category: { id: 6, name: 'Shoes', slug: 'shoes' }, categoryId: 6 },
  { id: 38, title: 'Puma Suede Classic', description: 'Classic suede upper with formstrip branding. Eva foam midsole for comfort. Puma rubber outsole for durability. Lace-up closure. Iconic design worn since 1968. Available in 20+ colorways.', price: 5999, discountPercentage: 25, rating: 4.5, stock: 150, brand: 'Puma', thumbnail: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400', images: [], category: { id: 6, name: 'Shoes', slug: 'shoes' }, categoryId: 6 },
  { id: 39, title: 'Skechers GOwalk 6', description: 'Lightweight knit mesh fabric upper. Goga Max insole for all-day comfort. Responsive 5GEN midsole cushioning. Ultra Go lightweight cushioning. Machine washable. Air-cooled memory foam insole.', price: 4999, discountPercentage: 30, rating: 4.6, stock: 200, brand: 'Skechers', thumbnail: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400', images: [], category: { id: 6, name: 'Shoes', slug: 'shoes' }, categoryId: 6 },
  { id: 40, title: 'Red Tape Formal Oxford', description: 'Genuine leather upper with oxford branding. Cushioned insole for all-day comfort. Leather lining for breathability. Lace-up closure. Rubber sole with anti-slip properties. Classic formal design.', price: 3499, discountPercentage: 35, rating: 4.3, stock: 250, brand: 'Red Tape', thumbnail: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400', images: [], category: { id: 6, name: 'Shoes', slug: 'shoes' }, categoryId: 6 },

  // Watches
  { id: 41, title: 'Apple Watch Series 9', description: 'S9 SiP chip for double tap gesture. Always-on Retina display. Blood oxygen and ECG sensors. Crash Detection and Fall Detection. 18-hour battery life. IP6X dust resistance and WR50.', price: 41900, discountPercentage: 5, rating: 4.8, stock: 80, brand: 'Apple', thumbnail: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=400', images: [], category: { id: 7, name: 'Watches', slug: 'watches' }, categoryId: 7 },
  { id: 42, title: 'Samsung Galaxy Watch 6 Classic', description: 'Rotating bezel with Super AMOLED display. Advanced sleep coaching and body composition. BIA sensor for accurate health data. 40-hour battery life. Wear OS 4 with Samsung One UI Watch 5.', price: 34999, discountPercentage: 12, rating: 4.7, stock: 60, brand: 'Samsung', thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400', images: [], category: { id: 7, name: 'Watches', slug: 'watches' }, categoryId: 7 },
  { id: 43, title: 'Garmin Fenix 7 Pro', description: 'Multi-band GPS with solar charging. 22-day battery life in smartwatch mode. Built-in LED flashlight. Physiological measurements including HRV status. Climb Pro for ascent planning. Sapphire crystal lens.', price: 79990, discountPercentage: 5, rating: 4.9, stock: 30, brand: 'Garmin', thumbnail: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400', images: [], category: { id: 7, name: 'Watches', slug: 'watches' }, categoryId: 7 },
  { id: 44, title: 'Titan Edge Ceramic', description: 'Ultra-slim 5.9mm case in ceramic and stainless steel. Automatic movement with exhibition caseback. Sapphire crystal with anti-reflective coating. 5ATM water resistance. Genuine leather strap.', price: 24995, discountPercentage: 10, rating: 4.6, stock: 45, brand: 'Titan', thumbnail: 'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=400', images: [], category: { id: 7, name: 'Watches', slug: 'watches' }, categoryId: 7 },
  { id: 45, title: 'Fossil Gen 6 Smartwatch', description: 'Snapdragon Wear 4100+ for 20% faster performance. SpO2, heart rate, NFC payments. AMOLED display with always-on. Alexa built-in. GPS connected. Rapid charging: 80% in 30 minutes.', price: 22995, discountPercentage: 30, rating: 4.4, stock: 70, brand: 'Fossil', thumbnail: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=400', images: [], category: { id: 7, name: 'Watches', slug: 'watches' }, categoryId: 7 },
  { id: 46, title: 'Casio G-Shock GA-2100', description: 'CasiOak design with carbon core guard structure. Shock resistant and 200m water resistance. World time 48 cities, 5 alarms, LED backlight. Tough Solar optional. 12/24-hour format. Anti-magnetic structure.', price: 8995, discountPercentage: 15, rating: 4.8, stock: 120, brand: 'Casio', thumbnail: 'https://images.unsplash.com/photo-1628248383225-bb48c02e79c1?w=400', images: [], category: { id: 7, name: 'Watches', slug: 'watches' }, categoryId: 7 },

  // Furniture
  { id: 47, title: 'Ergonomic Office Chair Premium', description: 'Mesh back with lumbar support and headrest. 4D adjustable armrests. Seat depth adjustment. Tilt lock mechanism with tension control. 360° swivel with heavy-duty casters. Supports up to 150kg.', price: 24999, discountPercentage: 20, rating: 4.7, stock: 40, brand: 'ErgoMax', thumbnail: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=400', images: [], category: { id: 8, name: 'Furniture', slug: 'furniture' }, categoryId: 8 },
  { id: 48, title: 'Standing Desk Electric', description: 'Electric height-adjustable desk from 60cm to 120cm. Anti-collision technology. 4 memory presets. 80kg load capacity. Solid 25mm tabletop. Cable management tray included. Whisper-quiet motor.', price: 34999, discountPercentage: 15, rating: 4.6, stock: 25, brand: 'FlexiDesk', thumbnail: 'https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?w=400', images: [], category: { id: 8, name: 'Furniture', slug: 'furniture' }, categoryId: 8 },
  { id: 49, title: 'L-Shaped Corner Sofa', description: 'Premium velvet upholstery with solid wood frame. Chaise lounge configuration. Pull-out sofa bed functionality. 3 scatter cushions included. Easy assembly. Available in 6 colors. 5-year warranty.', price: 49999, discountPercentage: 25, rating: 4.5, stock: 15, brand: 'HomeStyle', thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400', images: [], category: { id: 8, name: 'Furniture', slug: 'furniture' }, categoryId: 8 },
  { id: 50, title: 'King Size Bed Frame', description: 'Solid engineered wood frame with velvet upholstered headboard. Under-bed storage drawers. Slat base for mattress support. No box spring required. Easy assembly with tools included.', price: 39999, discountPercentage: 18, rating: 4.6, stock: 20, brand: 'WoodCraft', thumbnail: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=400', images: [], category: { id: 8, name: 'Furniture', slug: 'furniture' }, categoryId: 8 },
  { id: 51, title: 'Bookshelf 6-Tier Industrial', description: 'Metal frame with rustic wood shelves. Supports up to 30kg per shelf. Easy assembly with pre-drilled holes. Adjustable feet for uneven floors. 180cm height x 80cm width. Perfect for living room or office.', price: 9999, discountPercentage: 30, rating: 4.4, stock: 60, brand: 'IndustrialHome', thumbnail: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400', images: [], category: { id: 8, name: 'Furniture', slug: 'furniture' }, categoryId: 8 },

  // Kitchen
  { id: 52, title: 'Instant Pot Duo 7-in-1', description: 'Pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker and warmer. 14 smart programs. Delayed cooking up to 24 hours. 6-quart capacity. Dishwasher-safe inner pot.', price: 8999, discountPercentage: 25, rating: 4.8, stock: 200, brand: 'Instant Pot', thumbnail: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 53, title: 'Philips Air Fryer XXL', description: '3kg capacity with Rapid Air Technology. 90% less fat than traditional frying. 7 preset cooking programs. Digital touchscreen. Fat removal technology extracts and captures fat. Dishwasher-safe basket.', price: 14999, discountPercentage: 20, rating: 4.7, stock: 150, brand: 'Philips', thumbnail: 'https://images.unsplash.com/photo-1648897895047-02d6e1a1e84f?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 54, title: 'KitchenAid Stand Mixer', description: '4.8L stainless steel bowl with 10-speed settings. 59 touchpoints per revolution for thorough mixing. Tilt-head design for easy bowl access. 3 included attachments. Over 15 hub attachments available.', price: 49999, discountPercentage: 10, rating: 4.9, stock: 30, brand: 'KitchenAid', thumbnail: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 55, title: 'Nespresso Vertuo Next', description: 'Centrifusion technology for perfect extraction. 5 cup sizes from espresso to alto. 40-second heat-up time. Bluetooth connectivity for coffee customization. Compatible with 30+ Vertuo capsules.', price: 19999, discountPercentage: 15, rating: 4.6, stock: 80, brand: 'Nespresso', thumbnail: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 56, title: 'Prestige Pressure Cooker 5L', description: 'Tri-ply stainless steel body with aluminium core. Induction compatible base. Safety valve and pressure indicator. Metallic finish lid with safety features. 5-year warranty. ISI certified.', price: 2999, discountPercentage: 30, rating: 4.5, stock: 300, brand: 'Prestige', thumbnail: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 57, title: 'Vitamix Blender A3500', description: 'Smart technology with 5 program settings. 2.2HP motor for even the toughest ingredients. Self-cleaning in 60 seconds. Variable speed control with pulse feature. 64oz container. 10-year warranty.', price: 59999, discountPercentage: 8, rating: 4.9, stock: 20, brand: 'Vitamix', thumbnail: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },

  // Books
  { id: 58, title: 'Atomic Habits by James Clear', description: 'Proven framework for improving every day. Tiny changes, remarkable results. Over 15 million copies sold worldwide. Learn to build good habits and break bad ones. Practical strategies backed by science.', price: 499, discountPercentage: 35, rating: 4.9, stock: 1000, brand: 'Penguin', thumbnail: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400', images: [], category: { id: 10, name: 'Books', slug: 'books' }, categoryId: 10 },
  { id: 59, title: 'Rich Dad Poor Dad', description: 'Robert Kiyosaki\'s personal finance classic. What the rich teach their kids about money that the poor and middle class do not. 32 million copies sold. 20th anniversary edition with new foreword.', price: 399, discountPercentage: 40, rating: 4.7, stock: 800, brand: 'Warner Books', thumbnail: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400', images: [], category: { id: 10, name: 'Books', slug: 'books' }, categoryId: 10 },
  { id: 60, title: 'The Psychology of Money', description: 'Morgan Housel\'s timeless lessons on wealth, greed, and happiness. 19 short stories about the strangest thing in the world - money. Learn how to think better about risk and reward.', price: 449, discountPercentage: 30, rating: 4.8, stock: 900, brand: 'Jaico Publishing', thumbnail: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400', images: [], category: { id: 10, name: 'Books', slug: 'books' }, categoryId: 10 },

  // More Smartphones
  { id: 61, title: 'Nothing Phone 2a Plus', description: 'MediaTek Dimensity 7350 Pro with Glyph Interface. 50MP dual camera with Sony sensors. 6.7-inch AMOLED 120Hz display. 5000mAh battery with 50W charging. Nothing OS 2.6 based on Android 14.', price: 24999, discountPercentage: 10, rating: 4.5, stock: 100, brand: 'Nothing', thumbnail: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 62, title: 'Motorola Edge 50 Pro', description: 'Snapdragon 7 Gen 3 with 125W TurboPower charging. 6.7-inch pOLED 144Hz display. 50MP triple camera with OIS. IP68 water resistance. 4500mAh battery. Wooden finish back option.', price: 31999, discountPercentage: 15, rating: 4.4, stock: 75, brand: 'Motorola', thumbnail: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 63, title: 'iQOO 12 5G', description: 'Snapdragon 8 Gen 3 with LPDDR5X RAM. 50MP primary with Sony LYT-808 sensor. 144Hz AMOLED display with LTPO. 120W FlashCharge. V3 chip for gaming. 5000mAh battery.', price: 52999, discountPercentage: 10, rating: 4.7, stock: 65, brand: 'iQOO', thumbnail: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },

  // Tablets
  { id: 64, title: 'iPad Pro 12.9" M2', description: 'M2 chip for incredible performance. Ultra Retina XDR display with Liquid Retina. ProRes video recording. Wi-Fi 6E and 5G connectivity. Apple Pencil hover detection. Up to 2TB storage.', price: 112900, discountPercentage: 5, rating: 4.9, stock: 30, brand: 'Apple', thumbnail: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 65, title: 'Samsung Galaxy Tab S9 Ultra', description: 'Snapdragon 8 Gen 2 with 14.6-inch Dynamic AMOLED 2X display. S Pen included. IP68 rating. 12,000mAh battery. 45W wired and 15W wireless charging. 12GB RAM, 256GB storage.', price: 108999, discountPercentage: 8, rating: 4.8, stock: 20, brand: 'Samsung', thumbnail: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },

  // Smart Home
  { id: 66, title: 'Amazon Echo Dot 5th Gen', description: 'Improved audio with deeper bass and clearer vocals. Built-in Eero Wi-Fi extender. Temperature sensor. Motion detection. Alexa voice control. Connect to smart home devices. Stream music and podcasts.', price: 4499, discountPercentage: 40, rating: 4.6, stock: 500, brand: 'Amazon', thumbnail: 'https://images.unsplash.com/photo-1543512214-318c7553f230?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
  { id: 67, title: 'Google Nest Hub Max', description: '10-inch HD touchscreen smart display. Built-in Google Assistant. 6.5MP camera for video calls and Nest Cam. Stereo speakers with full range drivers. Photo frame mode. Control smart home devices.', price: 19999, discountPercentage: 15, rating: 4.5, stock: 80, brand: 'Google', thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },

  // Accessories
  { id: 68, title: 'Anker 100W GaN Charger', description: '3-port GaN charger (2 USB-C + 1 USB-A). PowerIQ 4.0 technology. Charges MacBook Pro in 90 min. Foldable prongs for travel. MultiVolt technology. Ultra-compact design. 5-year warranty.', price: 3999, discountPercentage: 20, rating: 4.8, stock: 300, brand: 'Anker', thumbnail: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 69, title: 'Logitech MX Master 3S', description: '8000 DPI sensor that works on glass. MagSpeed electromagnetic scrolling. USB-C charging with 70 days battery. 7 customizable buttons. Multi-device connectivity. App-specific profiles.', price: 9995, discountPercentage: 15, rating: 4.9, stock: 150, brand: 'Logitech', thumbnail: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 70, title: 'Samsung 49" Odyssey G9 Monitor', description: '5120x1440 DQHD curved gaming monitor. 240Hz refresh rate with 1ms response. QLED with HDR2000. G-Sync compatible and FreeSync Premium Pro. Mini LED with 2000 nits peak brightness. USB-C 90W.', price: 129999, discountPercentage: 10, rating: 4.7, stock: 12, brand: 'Samsung', thumbnail: 'https://images.unsplash.com/photo-1616763355603-9755a640a287?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },

  // More products to reach 100
  { id: 71, title: 'Dyson V15 Detect', description: 'Laser reveals microscopic dust. Intelligent suction that adapts. Whole-machine HEPA filtration. 60-minute runtime. LCD screen shows particle counts in real time. Up to 240AW of suction power.', price: 52900, discountPercentage: 10, rating: 4.8, stock: 40, brand: 'Dyson', thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 72, title: 'Kindle Paperwhite 11th Gen', description: '6.8-inch display with adjustable warm light. Waterproof (IPX8). 3-month battery life. 8GB or 16GB storage. Thin and light at only 205g. All-new flush-front design. USB-C charging.', price: 14999, discountPercentage: 20, rating: 4.8, stock: 200, brand: 'Amazon', thumbnail: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400', images: [], category: { id: 10, name: 'Books', slug: 'books' }, categoryId: 10 },
  { id: 73, title: 'DJI Mini 4 Pro Drone', description: '4K/60fps omnidirectional obstacle sensing. 34-minute flight time. Horizontal and vertical shooting. ActiveTrack 360° intelligent tracking. 48MP raw photos. Under 249g weight class.', price: 74999, discountPercentage: 5, rating: 4.8, stock: 20, brand: 'DJI', thumbnail: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400', images: [], category: { id: 4, name: 'Cameras', slug: 'cameras' }, categoryId: 4 },
  { id: 74, title: 'Lego Technic Bugatti Chiron', description: '3599-piece set with authentic Bugatti details. Functioning W16 engine with moving pistons. Working rear spoiler and gearbox. Built-in infotainment system model. Includes Chiron poster. Age 16+.', price: 39999, discountPercentage: 8, rating: 4.9, stock: 15, brand: 'Lego', thumbnail: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400', images: [], category: { id: 10, name: 'Books', slug: 'books' }, categoryId: 10 },
  { id: 75, title: 'Nike Pro Training Shorts', description: 'Dri-FIT ADV sweat-wicking fabric. 7-inch inseam with inner brief liner. Side pockets with zip closure. Mesh panels for ventilation. Elastic waistband with internal drawcord. Lightweight at 160g.', price: 3499, discountPercentage: 25, rating: 4.4, stock: 400, brand: 'Nike', thumbnail: 'https://images.unsplash.com/photo-1556906781-9a412961d28c?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 76, title: 'The Alchemist by Paulo Coelho', description: 'A magical fable about following your dream. 500 million copies sold in 80+ languages. A timeless classic about journeying toward your personal legend and listening to your heart.', price: 299, discountPercentage: 45, rating: 4.8, stock: 1500, brand: 'HarperCollins', thumbnail: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400', images: [], category: { id: 10, name: 'Books', slug: 'books' }, categoryId: 10 },
  { id: 77, title: 'Whey Protein Gold Standard', description: '24g protein per serving with 5.5g BCAAs and 4g glutamine. Less than 1g sugar per serving. Available in 20+ flavors. 900g (30 servings) or 2.27kg (73 servings). NSF certified for sport.', price: 4999, discountPercentage: 20, rating: 4.7, stock: 500, brand: 'Optimum Nutrition', thumbnail: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 78, title: 'BoAt Rockerz 550 Headphones', description: '40mm dynamic driver with BEAST mode. 20-hour battery with fast charge. Physical bass boost button. Foldable design with padded ear cushions. 3.5mm AUX and Bluetooth 5.0. Built-in mic.', price: 2999, discountPercentage: 50, rating: 4.3, stock: 400, brand: 'boAt', thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
  { id: 79, title: 'Noise ColorFit Pro 4 Smartwatch', description: '1.72-inch TFT LCD display with 600 nits. Stress monitor and SpO2 tracking. 100 sports modes. IP68 water resistance. 10-day battery life. Bluetooth calling with 60+ watch faces.', price: 3499, discountPercentage: 55, rating: 4.2, stock: 600, brand: 'Noise', thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400', images: [], category: { id: 7, name: 'Watches', slug: 'watches' }, categoryId: 7 },
  { id: 80, title: 'Zebronics Zeb-Pixaplay 20 Projector', description: 'Full HD 1080p with 5000 lumens brightness. Android 9.0 built-in with 2GB RAM. HDMI, USB, AV input. 200 inch projection size. Built-in 2x5W speakers. 30,000 hours lamp life. Auto keystone.', price: 24999, discountPercentage: 20, rating: 4.4, stock: 50, brand: 'Zebronics', thumbnail: 'https://images.unsplash.com/photo-1593078166039-c9878df5c520?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 81, title: 'Bajaj Majesty 1000TSS Mixer Grinder', description: '1000W motor with 3 stainless steel jars. 3-speed control with pulse function. Incher function for precise grinding. Anti-rust and rust-proof body. 2-year warranty. ISI marked for safety.', price: 3499, discountPercentage: 35, rating: 4.5, stock: 250, brand: 'Bajaj', thumbnail: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 82, title: 'Canon PIXMA G3770 Printer', description: 'MegaTank refillable ink system. Wireless printing from smartphone. 4-color CMYK ink. 4800x1200 dpi print quality. Borderless photo printing up to A4. Auto duplex printing. Cartridge-free system.', price: 14995, discountPercentage: 12, rating: 4.6, stock: 60, brand: 'Canon', thumbnail: 'https://images.unsplash.com/photo-1612815292064-b7cac5e80e56?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 83, title: 'Usha Mist Air Icy Tower Fan', description: '400mm sweep with 3-speed settings. Remote control with timer function. Sleep mode with auto speed reduction. Aroma cube for fragrance diffusion. Oscillation with 80° coverage. 5-year warranty.', price: 5999, discountPercentage: 25, rating: 4.4, stock: 150, brand: 'Usha', thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 84, title: 'Havells Prolife Turbo Water Purifier', description: '8L storage tank with UV+UF purification. Mineralizer with mineral cartridge. Indicator for filter change. In-tank UV sterilization. Wall-mountable. Works on municipal and borewell water.', price: 11999, discountPercentage: 20, rating: 4.5, stock: 80, brand: 'Havells', thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 85, title: 'Allen Solly Formal Trousers', description: 'Regular fit trousers in wrinkle-resistant fabric. Side and back pockets. Flat-front design. Easy-care machine washable. Available in grey, navy, beige, and black. Waist sizes 28-40.', price: 2499, discountPercentage: 40, rating: 4.4, stock: 350, brand: 'Allen Solly', thumbnail: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 86, title: 'Wildcraft Trek 45L Backpack', description: '45L capacity with laptop sleeve up to 17-inch. Hydration bladder compatible. Rain cover included. Adjustable shoulder and hip straps. Multiple external pockets. 900D polyester construction.', price: 3999, discountPercentage: 30, rating: 4.5, stock: 200, brand: 'Wildcraft', thumbnail: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 87, title: 'Fastrack Reflex Beat Smartwatch', description: '1.3-inch curved TFT display. 10-day battery life. 24/7 heart rate and SpO2 monitoring. IP68 water resistance. Menstrual cycle tracker. 100+ cloud watch faces. Android and iOS compatible.', price: 2995, discountPercentage: 45, rating: 4.2, stock: 500, brand: 'Fastrack', thumbnail: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=400', images: [], category: { id: 7, name: 'Watches', slug: 'watches' }, categoryId: 7 },
  { id: 88, title: 'HP LaserJet Pro M404dn', description: 'Print up to 40 pages per minute. First page out in under 7.4 seconds. 1200x1200 dpi print quality. Built-in Wi-Fi with dual-band. Auto duplex printing. 2.7-inch color touchscreen. 4GB eMMC storage.', price: 29999, discountPercentage: 10, rating: 4.7, stock: 40, brand: 'HP', thumbnail: 'https://images.unsplash.com/photo-1612815292064-b7cac5e80e56?w=400', images: [], category: { id: 2, name: 'Laptops', slug: 'laptops' }, categoryId: 2 },
  { id: 89, title: 'Godrej Interio Workstation Desk', description: 'L-shaped workstation with cable management. 1800x1500mm workspace. Height adjustable legs. Laminate finish with scratch resistance. Pre-assembled panels. 5-year warranty. Supports up to 75kg.', price: 29999, discountPercentage: 15, rating: 4.5, stock: 20, brand: 'Godrej', thumbnail: 'https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?w=400', images: [], category: { id: 8, name: 'Furniture', slug: 'furniture' }, categoryId: 8 },
  { id: 90, title: 'Orient Electric Tornado Fan', description: '1200mm sweep with high air delivery. 3-speed with remote control. Sleep timer and auto-off. Energy efficient brushless DC motor. 5-blade aerodynamic design. Dust-resistant blades. 2-year warranty.', price: 4499, discountPercentage: 28, rating: 4.4, stock: 180, brand: 'Orient', thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 91, title: 'Fitbit Charge 6', description: 'Built-in GPS with Google Maps. 7-day battery life. Heart rate, SpO2, EDA sensor. YouTube Music and Google Wallet. 40+ exercise modes. Active Zone Minutes. Stress management score.', price: 14999, discountPercentage: 20, rating: 4.6, stock: 100, brand: 'Fitbit', thumbnail: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400', images: [], category: { id: 7, name: 'Watches', slug: 'watches' }, categoryId: 7 },
  { id: 92, title: 'Saregama Carvaan Premium 2.0', description: '5000 pre-loaded songs by legendary singers. FM/AM/Bluetooth/USB. Carry handle for portability. 6W speakers with 360-degree sound. OLED display. 6-hour battery. Sanskrit/regional song support.', price: 11999, discountPercentage: 15, rating: 4.6, stock: 75, brand: 'Saregama', thumbnail: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
  { id: 93, title: 'Crossword Puzzle Books Set of 5', description: 'Brain-training crossword puzzles for adults. 500 puzzles from easy to expert level. Large print format for comfortable reading. Each book 192 pages with answer keys. Premium paper quality.', price: 999, discountPercentage: 25, rating: 4.5, stock: 500, brand: 'Crossword', thumbnail: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400', images: [], category: { id: 10, name: 'Books', slug: 'books' }, categoryId: 10 },
  { id: 94, title: 'Morphy Richards OTG 40L', description: '40L capacity with 5 heating modes. Rotisserie function included. Double glass door with interior light. Motorized rotisserie. 60-minute timer. 250°C maximum temperature. Bake, grill, broil, toast, defrost.', price: 7999, discountPercentage: 30, rating: 4.5, stock: 90, brand: 'Morphy Richards', thumbnail: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400', images: [], category: { id: 9, name: 'Kitchen', slug: 'kitchen' }, categoryId: 9 },
  { id: 95, title: 'Redmi Note 13 Pro+ 5G', description: 'MediaTek Dimensity 7200 Ultra with 200MP OIS camera. 120W HyperCharge in 19 minutes. 6.67-inch 1.5K AMOLED 120Hz display. IP68 rating. 5000mAh battery. Curved glass design.', price: 31999, discountPercentage: 12, rating: 4.5, stock: 120, brand: 'Redmi', thumbnail: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400', images: [], category: { id: 1, name: 'Smartphones', slug: 'smartphones' }, categoryId: 1 },
  { id: 96, title: 'Sony Bravia XR A80L OLED TV 55"', description: 'Cognitive Processor XR with OLED panel. XR OLED Contrast for infinite blacks. Acoustic Surface Audio+ technology. Google TV with hands-free voice control. HDMI 2.1 for PS5 / Xbox gaming. 120Hz refresh.', price: 174990, discountPercentage: 8, rating: 4.9, stock: 10, brand: 'Sony', thumbnail: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834b?w=400', images: [], category: { id: 8, name: 'Furniture', slug: 'furniture' }, categoryId: 8 },
  { id: 97, title: 'LG OLED C3 65" 4K TV', description: 'OLED evo panel with α9 Gen6 AI processor. Dolby Vision IQ and Dolby Atmos. NVIDIA G-Sync compatible. Game Optimizer with 4K 120Hz. webOS 23 smart TV. 4 HDMI 2.1 ports. Filmmaker Mode.', price: 189990, discountPercentage: 10, rating: 4.9, stock: 8, brand: 'LG', thumbnail: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834b?w=400', images: [], category: { id: 8, name: 'Furniture', slug: 'furniture' }, categoryId: 8 },
  { id: 98, title: 'Himalaya Neem Face Wash 200ml', description: 'Neem and turmeric formula for problem skin. Controls excess oil and prevents breakouts. Soap-free and gentle cleansing. Dermatologically tested. Paraben-free. No artificial colors. For all skin types.', price: 199, discountPercentage: 15, rating: 4.5, stock: 2000, brand: 'Himalaya', thumbnail: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 99, title: 'Park Avenue Good Morning Deo', description: 'Long-lasting 24-hour fragrance protection. Anti-perspirant formula. Refreshing citrus burst fragrance. Alcohol-free formula. No white marks. 220ml spray. Suitable for all skin types.', price: 299, discountPercentage: 20, rating: 4.3, stock: 1500, brand: 'Park Avenue', thumbnail: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400', images: [], category: { id: 5, name: 'Clothing', slug: 'clothing' }, categoryId: 5 },
  { id: 100, title: 'Bose SoundLink Flex', description: 'Waterproof and floatable Bluetooth speaker. PositionIQ technology adapts sound for position. 12-hour battery life. USB-C charging. Rugged silicone exterior with stainless steel. Works while charging.', price: 11990, discountPercentage: 10, rating: 4.8, stock: 80, brand: 'Bose', thumbnail: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400', images: [], category: { id: 3, name: 'Audio', slug: 'audio' }, categoryId: 3 },
];
